# Test Pandas Datetime Index

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt

In [2]:
days = 2000
rows = 1000

In [3]:
ini_date = '2010-01-01'

## 1.1 Numpy string method

In [4]:
dtindex1 = np.arange(np.datetime64(ini_date), 
                     np.datetime64(ini_date) 
                     + np.timedelta64(days, 'D')).astype('str')
dtindex1

array(['2010-01-01', '2010-01-02', '2010-01-03', ..., '2015-06-21',
       '2015-06-22', '2015-06-23'],
      dtype='<U28')

In [5]:
df1 = pd.DataFrame(np.array([np.arange(days) for x in range(rows)]), 
                   columns=dtindex1)

In [6]:
df1

,2010-01-01,2010-01-02,2010-01-03,2010-01-04,2010-01-05,2010-01-06,2010-01-07,2010-01-08,2010-01-09,2010-01-10,...,2015-06-14,2015-06-15,2015-06-16,2015-06-17,2015-06-18,2015-06-19,2015-06-20,2015-06-21,2015-06-22,2015-06-23
0,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
1,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
2,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
3,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
4,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
5,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
6,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
7,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
8,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
9,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
10,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
11,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
12,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
13,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
14,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
15,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
16,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
17,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
18,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
19,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
20,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
21,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
22,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
23,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
24,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
25,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
26,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
27,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
28,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
29,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
971,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
972,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
973,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
974,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
975,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
976,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
977,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
978,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
979,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
980,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
981,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
982,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
983,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
984,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
985,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
986,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
987,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
988,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
989,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
990,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
991,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
992,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
993,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
994,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
995,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
996,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
997,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
998,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
999,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999

In [7]:
df1.columns

Index(['2010-01-01', '2010-01-02', '2010-01-03', '2010-01-04', '2010-01-05',
       '2010-01-06', '2010-01-07', '2010-01-08', '2010-01-09', '2010-01-10',
       ...
       '2015-06-14', '2015-06-15', '2015-06-16', '2015-06-17', '2015-06-18',
       '2015-06-19', '2015-06-20', '2015-06-21', '2015-06-22', '2015-06-23'],
      dtype='object', length=2000)

In [8]:
df1['id'] = np.arange(rows)

In [9]:
df1

,2010-01-01,2010-01-02,2010-01-03,2010-01-04,2010-01-05,2010-01-06,2010-01-07,2010-01-08,2010-01-09,2010-01-10,...,2015-06-15,2015-06-16,2015-06-17,2015-06-18,2015-06-19,2015-06-20,2015-06-21,2015-06-22,2015-06-23,id
0,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,0
1,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,1
2,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,2
3,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,3
4,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,4
5,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,5
6,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,6
7,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,7
8,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,8
9,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,9
10,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,10
11,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,11
12,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,12
13,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,13
14,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,14
15,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,15
16,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,16
17,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,17
18,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,18
19,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,19
20,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,20
21,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,21
22,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,22
23,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,23
24,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,24
25,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,25
26,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,26
27,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,27
28,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,28
29,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,970
971,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,971
972,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,972
973,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,973
974,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,974
975,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,975
976,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,976
977,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,977
978,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,978
979,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,979
980,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,980
981,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,981
982,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,982
983,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,983
984,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,984
985,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,985
986,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,986
987,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,987
988,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,988
989,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,989
990,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,990
991,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,991
992,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,992
993,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,993
994,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,994
995,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,995
996,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,996
997,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,997
998,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,998
999,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,999

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Columns: 2001 entries, 2010-01-01 to id
dtypes: int32(2001)
memory usage: 7.6 MB

In [11]:
df1_f = pd.melt(df1, id_vars='id', var_name='date', value_name='visits')

In [12]:
df1_f

          id        date  visits
0          0  2010-01-01       0
1          1  2010-01-01       0
2          2  2010-01-01       0
3          3  2010-01-01       0
4          4  2010-01-01       0
5          5  2010-01-01       0
6          6  2010-01-01       0
7          7  2010-01-01       0
8          8  2010-01-01       0
9          9  2010-01-01       0
10        10  2010-01-01       0
11        11  2010-01-01       0
12        12  2010-01-01       0
13        13  2010-01-01       0
14        14  2010-01-01       0
15        15  2010-01-01       0
16        16  2010-01-01       0
17        17  2010-01-01       0
18        18  2010-01-01       0
19        19  2010-01-01       0
20        20  2010-01-01       0
21        21  2010-01-01       0
22        22  2010-01-01       0
23        23  2010-01-01       0
24        24  2010-01-01       0
25        25  2010-01-01       0
26        26  2010-01-01       0
27        27  2010-01-01       0
28        28  2010-01-01       0
29        29  2010-01-01       0
...      ...         ...     ...
1999970  970  2015-06-23    1999
1999971  971  2015-06-23    1999
1999972  972  2015-06-23    1999
1999973  973  2015-06-23    1999
1999974  974  2015-06-23    1999
1999975  975  2015-06-23    1999
1999976  976  2015-06-23    1999
1999977  977  2015-06-23    1999
1999978  978  2015-06-23    1999
1999979  979  2015-06-23    1999
1999980  980  2015-06-23    1999
1999981  981  2015-06-23    1999
1999982  982  2015-06-23    1999
1999983  983  2015-06-23    1999
1999984  984  2015-06-23    1999
1999985  985  2015-06-23    1999
1999986  986  2015-06-23    1999
1999987  987  2015-06-23    1999
1999988  988  2015-06-23    1999
1999989  989  2015-06-23    1999
1999990  990  2015-06-23    1999
1999991  991  2015-06-23    1999
1999992  992  2015-06-23    1999
1999993  993  2015-06-23    1999
1999994  994  2015-06-23    1999
1999995  995  2015-06-23    1999
1999996  996  2015-06-23    1999
1999997  997  2015-06-23    1999
1999998  998  2015-06-23    1999
1999999  999  2015-06-23    1999

[2000000 rows x 3 columns]

## 1.2 Pandas date_range method

In [13]:
dtindex2 = pd.date_range(ini_date,
                         periods=np.timedelta64(days,'D'), 
                         freq = 'D', unit = 'D')
dtindex2

DatetimeIndex(['2010-01-01', '2010-01-02', '2010-01-03', '2010-01-04',
               '2010-01-05', '2010-01-06', '2010-01-07', '2010-01-08',
               '2010-01-09', '2010-01-10',
               ...
               '2015-06-14', '2015-06-15', '2015-06-16', '2015-06-17',
               '2015-06-18', '2015-06-19', '2015-06-20', '2015-06-21',
               '2015-06-22', '2015-06-23'],
              dtype='datetime64[ns]', length=2000, freq='D')

In [14]:
df2 = pd.DataFrame(np.array([np.arange(days) for x in range(rows)]), 
                   columns=dtindex2)

In [15]:
df2

,2010-01-01 00:00:00,2010-01-02 00:00:00,2010-01-03 00:00:00,2010-01-04 00:00:00,2010-01-05 00:00:00,2010-01-06 00:00:00,2010-01-07 00:00:00,2010-01-08 00:00:00,2010-01-09 00:00:00,2010-01-10 00:00:00,...,2015-06-14 00:00:00,2015-06-15 00:00:00,2015-06-16 00:00:00,2015-06-17 00:00:00,2015-06-18 00:00:00,2015-06-19 00:00:00,2015-06-20 00:00:00,2015-06-21 00:00:00,2015-06-22 00:00:00,2015-06-23 00:00:00
0,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
1,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
2,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
3,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
4,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
5,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
6,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
7,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
8,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
9,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
10,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
11,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
12,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
13,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
14,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
15,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
16,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
17,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
18,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
19,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
20,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
21,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
22,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
23,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
24,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
25,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
26,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
27,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
28,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
29,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
971,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
972,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
973,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
974,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
975,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
976,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
977,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
978,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
979,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
980,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
981,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
982,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
983,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
984,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
985,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
986,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
987,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
988,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
989,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
990,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
991,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
992,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
993,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
994,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
995,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
996,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
997,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
998,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
999,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999

In [16]:
df2.columns

DatetimeIndex(['2010-01-01', '2010-01-02', '2010-01-03', '2010-01-04',
               '2010-01-05', '2010-01-06', '2010-01-07', '2010-01-08',
               '2010-01-09', '2010-01-10',
               ...
               '2015-06-14', '2015-06-15', '2015-06-16', '2015-06-17',
               '2015-06-18', '2015-06-19', '2015-06-20', '2015-06-21',
               '2015-06-22', '2015-06-23'],
              dtype='datetime64[ns]', length=2000, freq='D')

In [17]:
df2['id'] = np.arange(rows)

In [18]:
df2

,2010-01-01 00:00:00,2010-01-02 00:00:00,2010-01-03 00:00:00,2010-01-04 00:00:00,2010-01-05 00:00:00,2010-01-06 00:00:00,2010-01-07 00:00:00,2010-01-08 00:00:00,2010-01-09 00:00:00,2010-01-10 00:00:00,...,2015-06-15 00:00:00,2015-06-16 00:00:00,2015-06-17 00:00:00,2015-06-18 00:00:00,2015-06-19 00:00:00,2015-06-20 00:00:00,2015-06-21 00:00:00,2015-06-22 00:00:00,2015-06-23 00:00:00,id
0,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,0
1,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,1
2,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,2
3,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,3
4,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,4
5,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,5
6,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,6
7,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,7
8,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,8
9,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,9
10,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,10
11,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,11
12,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,12
13,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,13
14,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,14
15,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,15
16,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,16
17,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,17
18,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,18
19,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,19
20,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,20
21,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,21
22,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,22
23,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,23
24,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,24
25,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,25
26,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,26
27,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,27
28,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,28
29,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,970
971,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,971
972,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,972
973,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,973
974,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,974
975,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,975
976,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,976
977,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,977
978,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,978
979,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,979
980,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,980
981,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,981
982,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,982
983,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,983
984,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,984
985,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,985
986,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,986
987,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,987
988,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,988
989,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,989
990,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,990
991,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,991
992,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,992
993,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,993
994,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,994
995,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,995
996,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,996
997,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,997
998,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,998
999,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,999

In [19]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Columns: 2001 entries, 2010-01-01 00:00:00 to id
dtypes: int32(2001)
memory usage: 7.6 MB

In [20]:
df2_f = pd.melt(df2, id_vars='id', var_name='date', value_name='visits')

In [21]:
df2_f

          id       date  visits
0          0 2010-01-01       0
1          1 2010-01-01       0
2          2 2010-01-01       0
3          3 2010-01-01       0
4          4 2010-01-01       0
5          5 2010-01-01       0
6          6 2010-01-01       0
7          7 2010-01-01       0
8          8 2010-01-01       0
9          9 2010-01-01       0
10        10 2010-01-01       0
11        11 2010-01-01       0
12        12 2010-01-01       0
13        13 2010-01-01       0
14        14 2010-01-01       0
15        15 2010-01-01       0
16        16 2010-01-01       0
17        17 2010-01-01       0
18        18 2010-01-01       0
19        19 2010-01-01       0
20        20 2010-01-01       0
21        21 2010-01-01       0
22        22 2010-01-01       0
23        23 2010-01-01       0
24        24 2010-01-01       0
25        25 2010-01-01       0
26        26 2010-01-01       0
27        27 2010-01-01       0
28        28 2010-01-01       0
29        29 2010-01-01       0
...      ...        ...     ...
1999970  970 2015-06-23    1999
1999971  971 2015-06-23    1999
1999972  972 2015-06-23    1999
1999973  973 2015-06-23    1999
1999974  974 2015-06-23    1999
1999975  975 2015-06-23    1999
1999976  976 2015-06-23    1999
1999977  977 2015-06-23    1999
1999978  978 2015-06-23    1999
1999979  979 2015-06-23    1999
1999980  980 2015-06-23    1999
1999981  981 2015-06-23    1999
1999982  982 2015-06-23    1999
1999983  983 2015-06-23    1999
1999984  984 2015-06-23    1999
1999985  985 2015-06-23    1999
1999986  986 2015-06-23    1999
1999987  987 2015-06-23    1999
1999988  988 2015-06-23    1999
1999989  989 2015-06-23    1999
1999990  990 2015-06-23    1999
1999991  991 2015-06-23    1999
1999992  992 2015-06-23    1999
1999993  993 2015-06-23    1999
1999994  994 2015-06-23    1999
1999995  995 2015-06-23    1999
1999996  996 2015-06-23    1999
1999997  997 2015-06-23    1999
1999998  998 2015-06-23    1999
1999999  999 2015-06-23    1999

[2000000 rows x 3 columns]

## Pandas datetime but no frequency

In [22]:
dtindex3 = np.arange(np.datetime64(ini_date), 
                     np.datetime64(ini_date) 
                     + np.timedelta64(days, 'D'))
dtindex3

array(['2010-01-01', '2010-01-02', '2010-01-03', ..., '2015-06-21',
       '2015-06-22', '2015-06-23'], dtype='datetime64[D]')

In [23]:
df3 = pd.DataFrame(np.array([np.arange(days) for x in range(rows)]), 
                   columns=dtindex3)

In [24]:
df3

,2010-01-01 00:00:00,2010-01-02 00:00:00,2010-01-03 00:00:00,2010-01-04 00:00:00,2010-01-05 00:00:00,2010-01-06 00:00:00,2010-01-07 00:00:00,2010-01-08 00:00:00,2010-01-09 00:00:00,2010-01-10 00:00:00,...,2015-06-14 00:00:00,2015-06-15 00:00:00,2015-06-16 00:00:00,2015-06-17 00:00:00,2015-06-18 00:00:00,2015-06-19 00:00:00,2015-06-20 00:00:00,2015-06-21 00:00:00,2015-06-22 00:00:00,2015-06-23 00:00:00
0,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
1,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
2,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
3,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
4,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
5,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
6,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
7,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
8,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
9,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
10,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
11,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
12,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
13,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
14,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
15,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
16,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
17,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
18,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
19,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
20,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
21,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
22,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
23,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
24,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
25,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
26,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
27,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
28,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
29,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
971,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
972,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
973,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
974,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
975,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
976,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
977,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
978,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
979,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
980,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
981,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
982,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
983,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
984,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
985,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
986,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
987,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
988,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
989,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
990,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
991,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
992,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
993,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
994,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
995,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
996,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
997,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
998,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
999,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999

In [25]:
df3.columns

DatetimeIndex(['2010-01-01', '2010-01-02', '2010-01-03', '2010-01-04',
               '2010-01-05', '2010-01-06', '2010-01-07', '2010-01-08',
               '2010-01-09', '2010-01-10',
               ...
               '2015-06-14', '2015-06-15', '2015-06-16', '2015-06-17',
               '2015-06-18', '2015-06-19', '2015-06-20', '2015-06-21',
               '2015-06-22', '2015-06-23'],
              dtype='datetime64[ns]', length=2000, freq=None)

In [26]:
df3['id'] = np.arange(rows)

In [27]:
df3

,2010-01-01 00:00:00,2010-01-02 00:00:00,2010-01-03 00:00:00,2010-01-04 00:00:00,2010-01-05 00:00:00,2010-01-06 00:00:00,2010-01-07 00:00:00,2010-01-08 00:00:00,2010-01-09 00:00:00,2010-01-10 00:00:00,...,2015-06-15 00:00:00,2015-06-16 00:00:00,2015-06-17 00:00:00,2015-06-18 00:00:00,2015-06-19 00:00:00,2015-06-20 00:00:00,2015-06-21 00:00:00,2015-06-22 00:00:00,2015-06-23 00:00:00,id
0,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,0
1,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,1
2,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,2
3,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,3
4,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,4
5,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,5
6,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,6
7,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,7
8,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,8
9,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,9
10,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,10
11,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,11
12,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,12
13,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,13
14,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,14
15,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,15
16,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,16
17,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,17
18,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,18
19,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,19
20,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,20
21,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,21
22,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,22
23,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,23
24,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,24
25,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,25
26,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,26
27,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,27
28,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,28
29,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,970
971,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,971
972,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,972
973,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,973
974,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,974
975,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,975
976,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,976
977,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,977
978,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,978
979,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,979
980,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,980
981,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,981
982,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,982
983,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,983
984,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,984
985,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,985
986,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,986
987,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,987
988,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,988
989,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,989
990,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,990
991,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,991
992,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,992
993,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,993
994,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,994
995,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,995
996,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,996
997,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,997
998,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,998
999,0,1,2,3,4,5,6,7,8,9,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,999

In [28]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Columns: 2001 entries, 2010-01-01 00:00:00 to id
dtypes: int32(2001)
memory usage: 7.6 MB

In [29]:
df3_f = pd.melt(df3, id_vars='id', var_name='date', value_name='visits')

In [30]:
df3_f

          id       date  visits
0          0 2010-01-01       0
1          1 2010-01-01       0
2          2 2010-01-01       0
3          3 2010-01-01       0
4          4 2010-01-01       0
5          5 2010-01-01       0
6          6 2010-01-01       0
7          7 2010-01-01       0
8          8 2010-01-01       0
9          9 2010-01-01       0
10        10 2010-01-01       0
11        11 2010-01-01       0
12        12 2010-01-01       0
13        13 2010-01-01       0
14        14 2010-01-01       0
15        15 2010-01-01       0
16        16 2010-01-01       0
17        17 2010-01-01       0
18        18 2010-01-01       0
19        19 2010-01-01       0
20        20 2010-01-01       0
21        21 2010-01-01       0
22        22 2010-01-01       0
23        23 2010-01-01       0
24        24 2010-01-01       0
25        25 2010-01-01       0
26        26 2010-01-01       0
27        27 2010-01-01       0
28        28 2010-01-01       0
29        29 2010-01-01       0
...      ...        ...     ...
1999970  970 2015-06-23    1999
1999971  971 2015-06-23    1999
1999972  972 2015-06-23    1999
1999973  973 2015-06-23    1999
1999974  974 2015-06-23    1999
1999975  975 2015-06-23    1999
1999976  976 2015-06-23    1999
1999977  977 2015-06-23    1999
1999978  978 2015-06-23    1999
1999979  979 2015-06-23    1999
1999980  980 2015-06-23    1999
1999981  981 2015-06-23    1999
1999982  982 2015-06-23    1999
1999983  983 2015-06-23    1999
1999984  984 2015-06-23    1999
1999985  985 2015-06-23    1999
1999986  986 2015-06-23    1999
1999987  987 2015-06-23    1999
1999988  988 2015-06-23    1999
1999989  989 2015-06-23    1999
1999990  990 2015-06-23    1999
1999991  991 2015-06-23    1999
1999992  992 2015-06-23    1999
1999993  993 2015-06-23    1999
1999994  994 2015-06-23    1999
1999995  995 2015-06-23    1999
1999996  996 2015-06-23    1999
1999997  997 2015-06-23    1999
1999998  998 2015-06-23    1999
1999999  999 2015-06-23    1999

[2000000 rows x 3 columns]

In [31]:
df3_f['date']

0         2010-01-01
1         2010-01-01
2         2010-01-01
3         2010-01-01
4         2010-01-01
5         2010-01-01
6         2010-01-01
7         2010-01-01
8         2010-01-01
9         2010-01-01
10        2010-01-01
11        2010-01-01
12        2010-01-01
13        2010-01-01
14        2010-01-01
15        2010-01-01
16        2010-01-01
17        2010-01-01
18        2010-01-01
19        2010-01-01
20        2010-01-01
21        2010-01-01
22        2010-01-01
23        2010-01-01
24        2010-01-01
25        2010-01-01
26        2010-01-01
27        2010-01-01
28        2010-01-01
29        2010-01-01
             ...
1999970   2015-06-23
1999971   2015-06-23
1999972   2015-06-23
1999973   2015-06-23
1999974   2015-06-23
1999975   2015-06-23
1999976   2015-06-23
1999977   2015-06-23
1999978   2015-06-23
1999979   2015-06-23
1999980   2015-06-23
1999981   2015-06-23
1999982   2015-06-23
1999983   2015-06-23
1999984   2015-06-23
1999985   2015-06-23
1999986   2015-06-23
1999987   2015-06-23
1999988   2015-06-23
1999989   2015-06-23
1999990   2015-06-23
1999991   2015-06-23
1999992   2015-06-23
1999993   2015-06-23
1999994   2015-06-23
1999995   2015-06-23
1999996   2015-06-23
1999997   2015-06-23
1999998   2015-06-23
1999999   2015-06-23
Name: date, Length: 2000000, dtype: datetime64[ns]

## Merge

#### Datetime to datetime merge

In [32]:
target_df = df3_f[['id','date']]

In [33]:
target_df

          id       date
0          0 2010-01-01
1          1 2010-01-01
2          2 2010-01-01
3          3 2010-01-01
4          4 2010-01-01
5          5 2010-01-01
6          6 2010-01-01
7          7 2010-01-01
8          8 2010-01-01
9          9 2010-01-01
10        10 2010-01-01
11        11 2010-01-01
12        12 2010-01-01
13        13 2010-01-01
14        14 2010-01-01
15        15 2010-01-01
16        16 2010-01-01
17        17 2010-01-01
18        18 2010-01-01
19        19 2010-01-01
20        20 2010-01-01
21        21 2010-01-01
22        22 2010-01-01
23        23 2010-01-01
24        24 2010-01-01
25        25 2010-01-01
26        26 2010-01-01
27        27 2010-01-01
28        28 2010-01-01
29        29 2010-01-01
...      ...        ...
1999970  970 2015-06-23
1999971  971 2015-06-23
1999972  972 2015-06-23
1999973  973 2015-06-23
1999974  974 2015-06-23
1999975  975 2015-06-23
1999976  976 2015-06-23
1999977  977 2015-06-23
1999978  978 2015-06-23
1999979  979 2015-06-23
1999980  980 2015-06-23
1999981  981 2015-06-23
1999982  982 2015-06-23
1999983  983 2015-06-23
1999984  984 2015-06-23
1999985  985 2015-06-23
1999986  986 2015-06-23
1999987  987 2015-06-23
1999988  988 2015-06-23
1999989  989 2015-06-23
1999990  990 2015-06-23
1999991  991 2015-06-23
1999992  992 2015-06-23
1999993  993 2015-06-23
1999994  994 2015-06-23
1999995  995 2015-06-23
1999996  996 2015-06-23
1999997  997 2015-06-23
1999998  998 2015-06-23
1999999  999 2015-06-23

[2000000 rows x 2 columns]

In [34]:
target_df['date']

0         2010-01-01
1         2010-01-01
2         2010-01-01
3         2010-01-01
4         2010-01-01
5         2010-01-01
6         2010-01-01
7         2010-01-01
8         2010-01-01
9         2010-01-01
10        2010-01-01
11        2010-01-01
12        2010-01-01
13        2010-01-01
14        2010-01-01
15        2010-01-01
16        2010-01-01
17        2010-01-01
18        2010-01-01
19        2010-01-01
20        2010-01-01
21        2010-01-01
22        2010-01-01
23        2010-01-01
24        2010-01-01
25        2010-01-01
26        2010-01-01
27        2010-01-01
28        2010-01-01
29        2010-01-01
             ...
1999970   2015-06-23
1999971   2015-06-23
1999972   2015-06-23
1999973   2015-06-23
1999974   2015-06-23
1999975   2015-06-23
1999976   2015-06-23
1999977   2015-06-23
1999978   2015-06-23
1999979   2015-06-23
1999980   2015-06-23
1999981   2015-06-23
1999982   2015-06-23
1999983   2015-06-23
1999984   2015-06-23
1999985   2015-06-23
1999986   2015-06-23
1999987   2015-06-23
1999988   2015-06-23
1999989   2015-06-23
1999990   2015-06-23
1999991   2015-06-23
1999992   2015-06-23
1999993   2015-06-23
1999994   2015-06-23
1999995   2015-06-23
1999996   2015-06-23
1999997   2015-06-23
1999998   2015-06-23
1999999   2015-06-23
Name: date, Length: 2000000, dtype: datetime64[ns]

String to datetime

In [35]:
m1_df = target_df.merge(df1_f, how='left')

In [36]:
m1_df

          id                 date  visits
0          0  2010-01-01 00:00:00     NaN
1          1  2010-01-01 00:00:00     NaN
2          2  2010-01-01 00:00:00     NaN
3          3  2010-01-01 00:00:00     NaN
4          4  2010-01-01 00:00:00     NaN
5          5  2010-01-01 00:00:00     NaN
6          6  2010-01-01 00:00:00     NaN
7          7  2010-01-01 00:00:00     NaN
8          8  2010-01-01 00:00:00     NaN
9          9  2010-01-01 00:00:00     NaN
10        10  2010-01-01 00:00:00     NaN
11        11  2010-01-01 00:00:00     NaN
12        12  2010-01-01 00:00:00     NaN
13        13  2010-01-01 00:00:00     NaN
14        14  2010-01-01 00:00:00     NaN
15        15  2010-01-01 00:00:00     NaN
16        16  2010-01-01 00:00:00     NaN
17        17  2010-01-01 00:00:00     NaN
18        18  2010-01-01 00:00:00     NaN
19        19  2010-01-01 00:00:00     NaN
20        20  2010-01-01 00:00:00     NaN
21        21  2010-01-01 00:00:00     NaN
22        22  2010-01-01 00:00:00     NaN
23        23  2010-01-01 00:00:00     NaN
24        24  2010-01-01 00:00:00     NaN
25        25  2010-01-01 00:00:00     NaN
26        26  2010-01-01 00:00:00     NaN
27        27  2010-01-01 00:00:00     NaN
28        28  2010-01-01 00:00:00     NaN
29        29  2010-01-01 00:00:00     NaN
...      ...                  ...     ...
1999970  970  2015-06-23 00:00:00     NaN
1999971  971  2015-06-23 00:00:00     NaN
1999972  972  2015-06-23 00:00:00     NaN
1999973  973  2015-06-23 00:00:00     NaN
1999974  974  2015-06-23 00:00:00     NaN
1999975  975  2015-06-23 00:00:00     NaN
1999976  976  2015-06-23 00:00:00     NaN
1999977  977  2015-06-23 00:00:00     NaN
1999978  978  2015-06-23 00:00:00     NaN
1999979  979  2015-06-23 00:00:00     NaN
1999980  980  2015-06-23 00:00:00     NaN
1999981  981  2015-06-23 00:00:00     NaN
1999982  982  2015-06-23 00:00:00     NaN
1999983  983  2015-06-23 00:00:00     NaN
1999984  984  2015-06-23 00:00:00     NaN
1999985  985  2015-06-23 00:00:00     NaN
1999986  986  2015-06-23 00:00:00     NaN
1999987  987  2015-06-23 00:00:00     NaN
1999988  988  2015-06-23 00:00:00     NaN
1999989  989  2015-06-23 00:00:00     NaN
1999990  990  2015-06-23 00:00:00     NaN
1999991  991  2015-06-23 00:00:00     NaN
1999992  992  2015-06-23 00:00:00     NaN
1999993  993  2015-06-23 00:00:00     NaN
1999994  994  2015-06-23 00:00:00     NaN
1999995  995  2015-06-23 00:00:00     NaN
1999996  996  2015-06-23 00:00:00     NaN
1999997  997  2015-06-23 00:00:00     NaN
1999998  998  2015-06-23 00:00:00     NaN
1999999  999  2015-06-23 00:00:00     NaN

[2000000 rows x 3 columns]

Of course, doesn't work.

In [37]:
m2_df = target_df.merge(df2_f, how='left')

In [38]:
m2_df

          id       date  visits
0          0 2010-01-01       0
1          1 2010-01-01       0
2          2 2010-01-01       0
3          3 2010-01-01       0
4          4 2010-01-01       0
5          5 2010-01-01       0
6          6 2010-01-01       0
7          7 2010-01-01       0
8          8 2010-01-01       0
9          9 2010-01-01       0
10        10 2010-01-01       0
11        11 2010-01-01       0
12        12 2010-01-01       0
13        13 2010-01-01       0
14        14 2010-01-01       0
15        15 2010-01-01       0
16        16 2010-01-01       0
17        17 2010-01-01       0
18        18 2010-01-01       0
19        19 2010-01-01       0
20        20 2010-01-01       0
21        21 2010-01-01       0
22        22 2010-01-01       0
23        23 2010-01-01       0
24        24 2010-01-01       0
25        25 2010-01-01       0
26        26 2010-01-01       0
27        27 2010-01-01       0
28        28 2010-01-01       0
29        29 2010-01-01       0
...      ...        ...     ...
1999970  970 2015-06-23    1999
1999971  971 2015-06-23    1999
1999972  972 2015-06-23    1999
1999973  973 2015-06-23    1999
1999974  974 2015-06-23    1999
1999975  975 2015-06-23    1999
1999976  976 2015-06-23    1999
1999977  977 2015-06-23    1999
1999978  978 2015-06-23    1999
1999979  979 2015-06-23    1999
1999980  980 2015-06-23    1999
1999981  981 2015-06-23    1999
1999982  982 2015-06-23    1999
1999983  983 2015-06-23    1999
1999984  984 2015-06-23    1999
1999985  985 2015-06-23    1999
1999986  986 2015-06-23    1999
1999987  987 2015-06-23    1999
1999988  988 2015-06-23    1999
1999989  989 2015-06-23    1999
1999990  990 2015-06-23    1999
1999991  991 2015-06-23    1999
1999992  992 2015-06-23    1999
1999993  993 2015-06-23    1999
1999994  994 2015-06-23    1999
1999995  995 2015-06-23    1999
1999996  996 2015-06-23    1999
1999997  997 2015-06-23    1999
1999998  998 2015-06-23    1999
1999999  999 2015-06-23    1999

[2000000 rows x 3 columns]

Merge in 4 seconds

In [39]:
m3_df = target_df.merge(df3_f, how='left')

In [40]:
m3_df

          id       date  visits
0          0 2010-01-01       0
1          1 2010-01-01       0
2          2 2010-01-01       0
3          3 2010-01-01       0
4          4 2010-01-01       0
5          5 2010-01-01       0
6          6 2010-01-01       0
7          7 2010-01-01       0
8          8 2010-01-01       0
9          9 2010-01-01       0
10        10 2010-01-01       0
11        11 2010-01-01       0
12        12 2010-01-01       0
13        13 2010-01-01       0
14        14 2010-01-01       0
15        15 2010-01-01       0
16        16 2010-01-01       0
17        17 2010-01-01       0
18        18 2010-01-01       0
19        19 2010-01-01       0
20        20 2010-01-01       0
21        21 2010-01-01       0
22        22 2010-01-01       0
23        23 2010-01-01       0
24        24 2010-01-01       0
25        25 2010-01-01       0
26        26 2010-01-01       0
27        27 2010-01-01       0
28        28 2010-01-01       0
29        29 2010-01-01       0
...      ...        ...     ...
1999970  970 2015-06-23    1999
1999971  971 2015-06-23    1999
1999972  972 2015-06-23    1999
1999973  973 2015-06-23    1999
1999974  974 2015-06-23    1999
1999975  975 2015-06-23    1999
1999976  976 2015-06-23    1999
1999977  977 2015-06-23    1999
1999978  978 2015-06-23    1999
1999979  979 2015-06-23    1999
1999980  980 2015-06-23    1999
1999981  981 2015-06-23    1999
1999982  982 2015-06-23    1999
1999983  983 2015-06-23    1999
1999984  984 2015-06-23    1999
1999985  985 2015-06-23    1999
1999986  986 2015-06-23    1999
1999987  987 2015-06-23    1999
1999988  988 2015-06-23    1999
1999989  989 2015-06-23    1999
1999990  990 2015-06-23    1999
1999991  991 2015-06-23    1999
1999992  992 2015-06-23    1999
1999993  993 2015-06-23    1999
1999994  994 2015-06-23    1999
1999995  995 2015-06-23    1999
1999996  996 2015-06-23    1999
1999997  997 2015-06-23    1999
1999998  998 2015-06-23    1999
1999999  999 2015-06-23    1999

[2000000 rows x 3 columns]

Also, merge in 4 seconds

#### String to String merge

In [41]:
target1_df = df1_f[['id','date']]

In [42]:
target1_df['date']

0          2010-01-01
1          2010-01-01
2          2010-01-01
3          2010-01-01
4          2010-01-01
5          2010-01-01
6          2010-01-01
7          2010-01-01
8          2010-01-01
9          2010-01-01
10         2010-01-01
11         2010-01-01
12         2010-01-01
13         2010-01-01
14         2010-01-01
15         2010-01-01
16         2010-01-01
17         2010-01-01
18         2010-01-01
19         2010-01-01
20         2010-01-01
21         2010-01-01
22         2010-01-01
23         2010-01-01
24         2010-01-01
25         2010-01-01
26         2010-01-01
27         2010-01-01
28         2010-01-01
29         2010-01-01
              ...
1999970    2015-06-23
1999971    2015-06-23
1999972    2015-06-23
1999973    2015-06-23
1999974    2015-06-23
1999975    2015-06-23
1999976    2015-06-23
1999977    2015-06-23
1999978    2015-06-23
1999979    2015-06-23
1999980    2015-06-23
1999981    2015-06-23
1999982    2015-06-23
1999983    2015-06-23
1999984    2015-06-23
1999985    2015-06-23
1999986    2015-06-23
1999987    2015-06-23
1999988    2015-06-23
1999989    2015-06-23
1999990    2015-06-23
1999991    2015-06-23
1999992    2015-06-23
1999993    2015-06-23
1999994    2015-06-23
1999995    2015-06-23
1999996    2015-06-23
1999997    2015-06-23
1999998    2015-06-23
1999999    2015-06-23
Name: date, Length: 2000000, dtype: object

In [43]:
m1s_df = target1_df.merge(df1_f, how='left')

In [44]:
m1s_df

          id        date  visits
0          0  2010-01-01       0
1          1  2010-01-01       0
2          2  2010-01-01       0
3          3  2010-01-01       0
4          4  2010-01-01       0
5          5  2010-01-01       0
6          6  2010-01-01       0
7          7  2010-01-01       0
8          8  2010-01-01       0
9          9  2010-01-01       0
10        10  2010-01-01       0
11        11  2010-01-01       0
12        12  2010-01-01       0
13        13  2010-01-01       0
14        14  2010-01-01       0
15        15  2010-01-01       0
16        16  2010-01-01       0
17        17  2010-01-01       0
18        18  2010-01-01       0
19        19  2010-01-01       0
20        20  2010-01-01       0
21        21  2010-01-01       0
22        22  2010-01-01       0
23        23  2010-01-01       0
24        24  2010-01-01       0
25        25  2010-01-01       0
26        26  2010-01-01       0
27        27  2010-01-01       0
28        28  2010-01-01       0
29        29  2010-01-01       0
...      ...         ...     ...
1999970  970  2015-06-23    1999
1999971  971  2015-06-23    1999
1999972  972  2015-06-23    1999
1999973  973  2015-06-23    1999
1999974  974  2015-06-23    1999
1999975  975  2015-06-23    1999
1999976  976  2015-06-23    1999
1999977  977  2015-06-23    1999
1999978  978  2015-06-23    1999
1999979  979  2015-06-23    1999
1999980  980  2015-06-23    1999
1999981  981  2015-06-23    1999
1999982  982  2015-06-23    1999
1999983  983  2015-06-23    1999
1999984  984  2015-06-23    1999
1999985  985  2015-06-23    1999
1999986  986  2015-06-23    1999
1999987  987  2015-06-23    1999
1999988  988  2015-06-23    1999
1999989  989  2015-06-23    1999
1999990  990  2015-06-23    1999
1999991  991  2015-06-23    1999
1999992  992  2015-06-23    1999
1999993  993  2015-06-23    1999
1999994  994  2015-06-23    1999
1999995  995  2015-06-23    1999
1999996  996  2015-06-23    1999
1999997  997  2015-06-23    1999
1999998  998  2015-06-23    1999
1999999  999  2015-06-23    1999

[2000000 rows x 3 columns]

Similar speed

## Memory

In [45]:
df1_f.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 3 columns):
id        int32
date      object
visits    int32
dtypes: int32(2), object(1)
memory usage: 30.5+ MB

In [46]:
df2_f.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 3 columns):
id        int32
date      datetime64[ns]
visits    int32
dtypes: datetime64[ns](1), int32(2)
memory usage: 30.5 MB

In [47]:
df3_f.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 3 columns):
id        int32
date      datetime64[ns]
visits    int32
dtypes: datetime64[ns](1), int32(2)
memory usage: 30.5 MB

In [48]:
target_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 2 columns):
id      int32
date    datetime64[ns]
dtypes: datetime64[ns](1), int32(1)
memory usage: 22.9 MB

In [49]:
target1_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 2 columns):
id      int32
date    object
dtypes: int32(1), object(1)
memory usage: 22.9+ MB

In [50]:
m1_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2000000 entries, 0 to 1999999
Data columns (total 3 columns):
id        int32
date      object
visits    float64
dtypes: float64(1), int32(1), object(1)
memory usage: 53.4+ MB

In [51]:
m2_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2000000 entries, 0 to 1999999
Data columns (total 3 columns):
id        int32
date      datetime64[ns]
visits    int32
dtypes: datetime64[ns](1), int32(2)
memory usage: 45.8 MB

m3_df.info()
#Do not try this. It will crash.

In [52]:
m1s_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2000000 entries, 0 to 1999999
Data columns (total 3 columns):
id        int32
date      object
visits    int32
dtypes: int32(2), object(1)
memory usage: 45.8+ MB